updates workflow to only invalidate send updated files to s3

diff --git a/.github/workflows/integrate.yml b/.github/workflows/integrate.yml
--- a/.github/workflows/integrate.yml
+++ b/.github/workflows/integrate.yml
@@ -51,7 +51,43 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ secrets.AWS_REGION_NAME }}
       
-      - name: Sync to S3
+      - name: get updated files
         run: |
+          # allow grep to fail
+          set +e
+          FILES=$(git log --stat="1000" -1 | grep '|' | sed -e "s/public/./" | awk '{print $1}' | grep -e '\.jpg$')
+          set -e
           cd ./public
-          aws s3 sync . s3://${{ secrets.AWS_S3_BUCKET_NAME }}
+          for file in $FILES; do
+            echo $file
+            aws s3 cp $file s3://${{ secrets.AWS_S3_BUCKET_NAME }}
+          done
+
+      #- name: Sync to S3
+      #  run: |
+      #    cd ./public
+      #    aws s3 sync . s3://${{ secrets.AWS_S3_BUCKET_NAME }}
+  invalidate-cloudfront-cache:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: get updated files
+        run: |
+          # allow grep to fail
+          set +e
+          FILES=$(git log --stat="1000" -1 | grep '|' | sed -e "s/public//" | awk '{print $1}' | grep -e '\.jpg$')
+          set -e
+          [ -z "$FILES" ] && touch .updated_files && exit 0
+          for file in $FILES; do
+            echo $file
+          done | sort | uniq | tr '\n' ' ' > .updated_files
+          cat .updated_files
+      
+      - name: Invalidate CloudFront
+        uses: chetan/invalidate-cloudfront-action@v2
+        env:
+          DISTRIBUTION: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION }}
+          PATHS_FROM: .updated_files
+          AWS_REGION: 'global'
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
