revert to previous version

diff --git a/.github/workflows/integrate.yml b/.github/workflows/integrate.yml
--- a/.github/workflows/integrate.yml
+++ b/.github/workflows/integrate.yml
@@ -64,24 +64,25 @@ jobs:
         with:
           persist-credentials: false
       
-      #- name: fetch files
-      #  run: |
-      #    cd ./public
-      #    # allow grep to fail
-      #    set +e
-      #    FILES=$(find . -maxdepth 2 -type f | sed -e "s/.//" | grep -e '\.jpg$')
-      #    set -e
-      #    [ -z "$FILES" ] && touch .updated_files && exit 0
-      #    for file in $FILES; do
-      #      echo $file
-      #    done | sort | uniq | tr '\n' ' ' > .updated_files
-      #    cat .updated_files
+      - name: fetch files
+        run: |
+          cd ./public
+          find . -maxdepth 2 -type f | sed -e "s/.//" | sort > .updated_files
+          # allow grep to fail
+          set +e
+          FILES=$(find . -maxdepth 2 -type f | sed -e "s/.//" | grep -e '\.jpg$')
+          set -e
+          [ -z "$FILES" ] && touch .updated_files && exit 0
+          for file in $FILES; do
+            echo $file
+          done | sort | uniq | tr '\n' ' ' > .updated_files
+          cat .updated_files
       
       - name: Invalidate CloudFront
-        uses: awact/cloudfront-action@master
+        uses: chetan/invalidate-cloudfront-action@v2
         env:
-          SOURCE_PATH: './public'
+          DISTRIBUTION: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION }}
+          PATHS_FROM: .updated_files
           AWS_REGION: 'global'
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          DISTRIBUTION_ID: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION }}
